#!/bin/bash

if [ "$#" -ne 2 ]; then
  echo "Uso: $0 <nome_da_base_de_dados> <ficheiro_de_destino.sql>"
  exit 1
fi

BASE_DADOS="$1"
FICHEIRO_DESTINO="$2"


mysqldump -u root -p "$BASE_DADOS" > "$FICHEIRO_DESTINO"

if [ $? -eq 0 ]; then
  echo "Backup de '$BASE_DADOS' feito em '$FICHEIRO_DESTINO'"
else
  echo "Erro ao salvar a base de dados, verifica:"
  echo "1. Se a password está correta"
  echo "2. Se a base '$BASE_DADOS' existe"
  exit 3
fi
